const fs = require('fs');
const path = require('path');

const namesPath = 'D:/Allah-names/husna-mobile/data/names.json';
const names = JSON.parse(fs.readFileSync(namesPath, 'utf8'));

const frenchMeanings = [
    "Allah (Dieu, l'Être suprême)",
    "Ar-Rahmân (Le Tout Miséricordieux)",
    "Ar-Rahîm (Le Très Miséricordieux)",
    "Al-Malik (Le Souverain, Le Roi)",
    "Al-Quddûs (Le Saint, Le Pur)",
    "As-Salâm (La Paix, L'Exempt de tout défaut)",
    "Al-Mu'min (La Sauvegarde, L'Infuseur de foi)",
    "Al-Muhaymin (Le Préservateur, Le Protecteur)",
    "Al-'Azîz (Le Tout-Puissant, Le Fort, L'Estimé)",
    "Al-Jabbâr (Le Contraignant, L'Imposant)",
    "Al-Mutakabbir (L'Orgueilleux, Le Suprême)",
    "Al-Khâliq (Le Créateur)",
    "Al-Bâri' (Le Producteur, L'Initiateur)",
    "Al-Musawwir (Le Formateur)",
    "Al-Ghaffâr (Le Grand Pardonneur)",
    "Al-Qahhâr (Le Dominateur suprême)",
    "Al-Wahhâb (Le Très Généreux)",
    "Ar-Razzâq (Le Grand Pourvoyeur)",
    "Al-Fattâh (L'Octroyeur, Celui qui accorde la victoire)",
    "Al-'Alîm (L'Omniscient, Celui qui sait tout)",
    "Al-Qâbidh (Celui qui restreint)",
    "Al-Bâsit (Celui qui étend Sa générosité)",
    "Al-Khâfidh (Celui qui abaisse)",
    "Ar-Râfi' (Celui qui élève)",
    "Al-Mu'izz (Celui qui rend puissant)",
    "Al-Moudhill (Celui qui humilie les fiers)",
    "As-Samî' (L'Audient, Celui qui entend tout)",
    "Al-Basîr (Le Voyant, Celui qui voit tout)",
    "Al-Hakam (Le Juge)",
    "Al-'Adl (Le Juste)",
    "Al-Latîf (Le Subtil)",
    "Al-Khabîr (Le Parfaitement Connaisseur)",
    "Al-Halîm (L'Indulgent)",
    "Al-'Azhîm (L'Immense)",
    "Al-Ghafûr (Le Pardonneur)",
    "Ach-Chakûr (Le Très Reconnaissant)",
    "Al-'Aliyy (Le Très Haut, L'Élevé)",
    "Al-Kabîr (Le Grand)",
    "Al-Hafîzh (Le Gardien)",
    "Al-Muqît (Le Nourrisseur par excellence)",
    "Al-Hassîb (Celui qui tient les comptes)",
    "Al-Jalîl (Le Majestueux)",
    "Al-Karîm (Le Généreux)",
    "Ar-Raqîb (L'Observateur suprême)",
    "Al-Mujîb (Celui qui exauce les invocations)",
    "Al-Wâsi' (Le Détenteur des largesses)",
    "Al-Hakîm (Le Sage par excellence)",
    "Al-Wadûd (L'Affectueux)",
    "Al-Majîd (Le Glorieux, Le Majestueux)",
    "Al-Bâ'ith (Celui qui ressuscite)",
    "Ach-Chahîd (Le Témoin de toute chose)",
    "Al-Haqq (Le Vrai)",
    "Al-Wakîl (Le Garant par excellence)",
    "Al-Qawiyy (Le Puissant, Le Très Fort)",
    "Al-Matîn (L'Inébranlable, Le Très Ferme)",
    "Al-Walîy (Le Maître ou l'Allié)",
    "Al-Hamîd (Le Digne de louanges)",
    "Al-Muhsî (Celui qui dénombre toute chose)",
    "Al-Mubdi' (L'Initiateur)",
    "Al-Mu'îd (Celui qui redonne existence après la mort)",
    "Al-Muhyî (Celui qui fait vivre)",
    "Al-Mumît (Celui qui fait mourir)",
    "Al-Hayy (Le Vivant)",
    "Al-Qayyûm (Celui qui subsiste par Lui-même)",
    "Al-Wâjid (L'Opulent)",
    "Al-Mâjid (Le Glorieux, Le Majestueux)",
    "Al-Wâhid (L'Unique)",
    "Al-Ahad (L'Unique)",
    "As-Samad (Le Seul à être imploré pour nos besoins)",
    "Al-Qâdir (Le Capable de toute chose)",
    "Al-Muqtadir (Celui qui fixe la mesure)",
    "Al-Muqaddim (Celui qui fait avancer)",
    "Al-Mu'akhkhir (Celui qui retarde)",
    "Al-Awwal (Le Premier)",
    "Al-Âkhir (Le Dernier)",
    "Azh-Zhâhir (L'Apparent)",
    "Al-Bâtin (Le Caché)",
    "Al-Wâlî (Le Maître, Le Gouverneur)",
    "Al-Muta'âlî (Le Transcendant, L'Exalté)",
    "Al-Barr (Le Charitable, Le Bienveillant)",
    "At-Tawwâb (L'Accueillant au repentir)",
    "Al-Muntaqim (Le Vengeur)",
    "Al-'Afuww (Le Grand Pardonneur)",
    "Ar-Ra'ûf (Le Clément)",
    "Mâlik-ul-Mulk (Le Maître absolu du Royaume)",
    "Dhul-Jalâli wal-Ikrâm (Le Détenteur de la Majesté)",
    "Al-Muqsit (L'Équitable)",
    "Al-Jâmi' (Celui qui réunit)",
    "Al-Ghanîy (Le Riche)",
    "Al-Mughnî (Celui qui confère la suffisance)",
    "Al-Mâni' (Celui qui retient)",
    "Ad-Dârr (Celui qui peut nuire)",
    "An-Nâfi' (Le Bénéfique)",
    "An-Nûr (La Lumière)",
    "Al-Hâdî (Le Guide)",
    "Al-Badî' (L'Inventeur)",
    "Al-Bâqî (Le Permanent)",
    "Al-Wârith (L'Héritier)",
    "Ar-Rachîd (Le Bien-guidé)",
    "As-Sabûr (Le Patient)"
];

names.forEach((name, index) => {
    // Skip index 0 (Allah) as names.json starts from id 1 (Ar-Rahman)
    if (frenchMeanings[index + 1]) {
        name.meaning_fr = frenchMeanings[index + 1];
    }
});

fs.writeFileSync(namesPath, JSON.stringify(names, null, 4));
console.log('Successfully added French meanings to all names.');
