const fs = require('fs');
const path = require('path');

const namesPath = path.join(__dirname, 'data', 'names.json');
const rawData = fs.readFileSync(namesPath, 'utf8');
const names = JSON.parse(rawData);

const translations = {
    "1": { ar: "الله", bs: "Allah, Bog" },
    "2": { ar: "الرحمن", bs: "Svemilosni" },
    "3": { ar: "الرحيم", bs: "Samilosni" },
    "4": { ar: "الملك", bs: "Vladar, Suvereni" },
    "5": { ar: "القدوس", bs: "Sveti, Najčistiji" },
    "6": { ar: "السلام", bs: "Izvor mira i spasa" },
    "7": { ar: "المؤمن", bs: "Pouzdani, Koji daje sigurnost" },
    "8": { ar: "المهيمن", bs: "Zaštitnik, Koji sve pazi i prati" },
    "9": { ar: "العزيز", bs: "Silni, Snažni" },
    "10": { ar: "الجبار", bs: "Silni, Koji sve potčinjava" },
    "11": { ar: "المتكبر", bs: "Gordi, Veličanstveni" },
    "12": { ar: "الخالق", bs: "Stvoritelj" },
    "13": { ar: "البارئ", bs: "Koji divno stvara" },
    "14": { ar: "المصور", bs: "Koji likove daje" },
    "15": { ar: "الغفار", bs: "Onaj Koji mnogo prašta" },
    "16": { ar: "القهار", bs: "Onaj Koji nadvladava" },
    "17": { ar: "الوهاب", bs: "Onaj Koji obilno daruje" },
    "18": { ar: "الرزاق", bs: "Onaj Koji opskrbljuje" },
    "19": { ar: "الفتاح", bs: "Onaj Koji otvara i rješava" },
    "20": { ar: "العليم", bs: "Sveznajući" },
    "21": { ar: "القابض", bs: "Onaj Koji steže i susteže" },
    "22": { ar: "الباسط", bs: "Onaj Koji pruža i širi" },
    "23": { ar: "الخافض", bs: "Onaj Koji spušta" },
    "24": { ar: "الرافع", bs: "Onaj Koji uzdiže" },
    "25": { ar: "المعز", bs: "Onaj Koji uzvisuje" },
    "26": { ar: "المذل", bs: "Onaj Koji unižava" },
    "27": { ar: "السميع", bs: "Svečujući" },
    "28": { ar: "البصير", bs: "Svevideći" },
    "29": { ar: "الحكم", bs: "Sudija" },
    "30": { ar: "العدل", bs: "Pravedni" },
    "31": { ar: "اللطيف", bs: "Dobri, Milostivi" },
    "32": { ar: "الخبير", bs: "O svemu obaviješteni" },
    "33": { ar: "الحليم", bs: "Blagi, Strpljivi" },
    "34": { ar: "العظيم", bs: "Veličanstveni" },
    "35": { ar: "الغفور", bs: "Onaj Koji mnogo prašta" },
    "36": { ar: "الشكور", bs: "Zahvalni" },
    "37": { ar: "العلي", bs: "Uzvišeni" },
    "38": { ar: "الكبير", bs: "Veliki" },
    "39": { ar: "الحفيظ", bs: "Čuvar" },
    "40": { ar: "المقيت", bs: "Onaj Koji pazi i izdržava" },
    "41": { ar: "الحسيب", bs: "Onaj Koji obračun svodi" },
    "42": { ar: "الجليل", bs: "Veličanstveni" },
    "43": { ar: "الكريم", bs: "Plemeniti" },
    "44": { ar: "الرقيب", bs: "Onaj Koji na sve motri" },
    "45": { ar: "المجيب", bs: "Onaj Koji molitve uslišava" },
    "46": { ar: "الواسع", bs: "Sveobuhvatni" },
    "47": { ar: "الحكيم", bs: "Mudri" },
    "48": { ar: "الودود", bs: "Onaj Koji voli" },
    "49": { ar: "المجيد", bs: "Slavljeni" },
    "50": { ar: "الباعث", bs: "Onaj Koji proživljava" },
    "51": { ar: "الشهيد", bs: "Svjedok svega" },
    "52": { ar: "الحق", bs: "Istina" },
    "53": { ar: "الوكيل", bs: "Zaštitnik, Oslonac" },
    "54": { ar: "القوي", bs: "Snažni" },
    "55": { ar: "المتين", safegu: "Čvrsti" },
    "56": { ar: "الولي", bs: "Zaštitnik, Prijatelj" },
    "57": { ar: "الحميد", bs: "Hvaljeni" },
    "58": { ar: "المحصي", bs: "Onaj Koji sve obuhvata i broji" },
    "59": { ar: "المبدئ", bs: "Početni Stvoritelj" },
    "60": { ar: "المعيد", bs: "Onaj Koji sve vraća na početak" },
    "61": { ar: "المحيي", bs: "Onaj Koji život daje" },
    "62": { ar: "المميت", bs: "Onaj Koji smrt daje" },
    "63": { ar: "الحي", bs: "Živi" },
    "64": { ar: "القيوم", bs: "Vječni, Održavatelj" },
    "65": { ar: "الواجد", bs: "Bogati, Koji sve ima" },
    "66": { ar: "الماجد", bs: "Slavni" },
    "67": { ar: "الواحد", bs: "Jedini" },
    "68": { ar: "الصمد", bs: "Utočište svakom" },
    "69": { ar: "القادر", bs: "Moćni" },
    "70": { ar: "المقتدر", bs: "Svemoćni" },
    "71": { ar: "المقدم", bs: "Onaj Koji unapređuje" },
    "72": { ar: "المؤخر", bs: "Onaj Koji unazađuje" },
    "73": { ar: "الأول", bs: "Prvi" },
    "74": { ar: "الآخر", bs: "Posljednji" },
    "75": { ar: "الظاهر", bs: "Vidljivi" },
    "76": { ar: "الباطن", bs: "Skriveni" },
    "77": { ar: "الوالي", bs: "Upravitelj" },
    "78": { ar: "المتعالي", bs: "Preuzvišeni" },
    "79": { ar: "البر", bs: "Dobročinitelj" },
    "80": { ar: "التواب", bs: "Onaj Koji prima pokajanje" },
    "81": { ar: "المنتقم", bs: "Osvetnik" },
    "82": { ar: "العفو", bs: "Onaj Koji prašta" },
    "83": { ar: "الرؤوف", bs: "Samilosni" },
    "84": { ar: "مالك الملك", bs: "Vladar svih svjetova" },
    "85": { ar: "ذو الجلال والإكرام", bs: "Gospodar veličanstva i plemenitosti" },
    "86": { ar: "المقسط", bs: "Pravedni" },
    "87": { ar: "الجامع", bs: "Onaj Koji sve okuplja" },
    "88": { ar: "الغني", bs: "Bogati, Neovisni" },
    "89": { ar: "المغني", bs: "Onaj Koji bogatstvom obasipa" },
    "90": { ar: "المانع", bs: "Onaj Koji sprečava i uskraćuje" },
    "91": { ar: "الضار", bs: "Onaj Koji štetu stvara" },
    "92": { ar: "النافع", bs: "Onaj Koji korist stvara" },
    "93": { ar: "النور", bs: "Svjetlost" },
    "94": { ar: "الهادي", bs: "Uputitelj" },
    "95": { ar: "البديع", bs: "Inovator, Besprimjerni Tvorac" },
    "96": { ar: "الباقي", bs: "Vječni" },
    "97": { ar: "الوارث", bs: "Nasljednik svega" },
    "98": { ar: "الرشيد", bs: "Vodič na Pravi put" },
    "99": { ar: "الصبور", bs: "Strpljivi" }
};

const extendedNames = names.map(n => {
    const trans = translations[n.id.toString()];
    return {
        ...n,
        meaning_en: n.meaning, // Keep current meaning as English
        meaning_ar: trans ? trans.ar : n.arabic, // Arabic meaning is often just the trait
        meaning_bs: trans ? (trans.bs || trans.safegu || "Nepoznato") : n.meaning
    };
});

fs.writeFileSync(namesPath, JSON.stringify(extendedNames, null, 4));
console.log('Successfully updated names.json with Arabic and Bosnian meanings.');
